# Generated by Django 4.1.5 on 2023-03-31 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhome', '0002_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.IntegerField(choices=[(0, 'Ландшафтний дизай'), (1, "Облаштування інтер'єру"), (2, 'Клінінг'), (3, 'Охоронна система'), (3, "Дизайн інтер'єру")]),
        ),
    ]
